import { MongoClient, ObjectId } from 'mongodb';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load server .env
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017';
const DB_NAME = process.env.MONGODB_DB_NAME || 'wibby';
const UPLOADS_DIR = fs.existsSync(path.resolve(__dirname, '../../uploads')) 
  ? path.resolve(__dirname, '../../uploads')
  : path.resolve(__dirname, '../../../uploads');

function formatBytes(bytes) {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

function getUploadStats(dirPath) {
  let totalFiles = 0;
  let totalSize = 0;
  const filesList = [];

  function scan(currentDir) {
    if (!fs.existsSync(currentDir)) return;
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        scan(full);
      } else if (entry.isFile()) {
        totalFiles++;
        const stat = fs.statSync(full);
        totalSize += stat.size;
        filesList.push({
          path: full,
          relPath: path.relative(dirPath, full),
          size: stat.size,
          mtime: stat.mtime
        });
      }
    }
  }

  scan(dirPath);
  return { totalFiles, totalSize, filesList };
}

async function inspectStorage(db) {
  console.log('\n======================================================');
  console.log('       🔍 WIBBY STORAGE & DATABASE AUDIT INSPECTION    ');
  console.log('======================================================\n');

  // 1. Database Collections
  const collections = ['users', 'conversations', 'messages', 'calls', 'stories', 'pairingCodes'];
  console.log('📊 DATABASE COLLECTIONS:');
  for (const col of collections) {
    try {
      const count = await db.collection(col).countDocuments();
      console.log(`  • ${col.padEnd(16)}: ${count} documents`);
    } catch {
      console.log(`  • ${col.padEnd(16)}: 0 documents`);
    }
  }

  // 2. Physical File Storage
  const { totalFiles, totalSize, filesList } = getUploadStats(UPLOADS_DIR);
  console.log(`\n📁 PHYSICAL UPLOADS DIRECTORY (${UPLOADS_DIR}):`);
  console.log(`  • Total Stored Files : ${totalFiles}`);
  console.log(`  • Total Storage Size : ${formatBytes(totalSize)}`);

  // Detect test media fixtures vs active media
  const testPatterns = [/test/i, /burst/i, /voice_safari/i, /voice_firefox/i, /nowave/i, /phase8/i];
  const testFiles = filesList.filter(f => testPatterns.some(p => p.test(f.relPath)));
  console.log(`  • Automated Test Files Detected: ${testFiles.length} (${formatBytes(testFiles.reduce((s, f) => s + f.size, 0))})`);

  // 3. Active Users & Conversations
  console.log('\n👥 ACTIVE USERS IN DATABASE:');
  const users = await db.collection('users').find({}).limit(10).toArray();
  for (const u of users) {
    console.log(`  • [${u.username || 'unnamed'}] display: "${u.display_name || u.displayName || 'N/A'}" uid: ${u.firebaseUid}`);
  }

  console.log('\n💬 CONVERSATIONS:');
  const convos = await db.collection('conversations').find({}).toArray();
  for (const c of convos) {
    const msgCount = await db.collection('messages').countDocuments({ conversationId: c._id });
    console.log(`  • Conversation ID: ${c._id} (Members: ${c.members?.length || 0}) -> ${msgCount} messages`);
  }

  console.log('\n======================================================\n');
}

async function cleanTestFixtures(db) {
  console.log('\n🧹 CLEANING AUTOMATED TEST FIXTURES...');
  
  // 1. Remove mock test user records (e.g. test_uid_*, mock test accounts)
  const testUserRes = await db.collection('users').deleteMany({
    $or: [
      { firebaseUid: { $regex: /^test_/i } },
      { username: { $regex: /^test_mock/i } }
    ]
  });
  console.log(`  ✓ Removed ${testUserRes.deletedCount} mock test user accounts`);

  // 2. Clean automated call test fixtures (calls generated by test scripts)
  const testCallsRes = await db.collection('calls').deleteMany({
    $or: [
      { callerUid: { $regex: /^test_/i } },
      { receiverUid: { $regex: /^test_/i } },
      { conversationId: 'test_convo_phase8' }
    ]
  });
  console.log(`  ✓ Removed ${testCallsRes.deletedCount} automated test call records`);

  // 3. Clean physical test media files
  const { filesList } = getUploadStats(UPLOADS_DIR);
  const testPatterns = [/test1\.png/i, /voice_burst/i, /voice_safari/i, /voice_firefox/i, /voice_nowave/i, /test_call_phase8/i];
  let deletedFilesCount = 0;
  let freedBytes = 0;

  for (const f of filesList) {
    if (testPatterns.some(p => p.test(f.relPath))) {
      try {
        fs.unlinkSync(f.path);
        deletedFilesCount++;
        freedBytes += f.size;
      } catch (err) {
        console.warn(`    Failed to delete ${f.relPath}:`, err.message);
      }
    }
  }

  console.log(`  ✓ Cleaned ${deletedFilesCount} physical test media files (${formatBytes(freedBytes)} freed)`);
  console.log('\n✅ Test fixture cleaning complete. Real user data and conversations preserved!\n');
}

async function wipeAll(db) {
  console.log('\n⚠️  WIPING ALL DATABASE COLLECTIONS AND UPLOADS...');
  
  const collections = ['users', 'conversations', 'messages', 'calls', 'stories', 'pairingCodes', 'test'];
  for (const col of collections) {
    try {
      const res = await db.collection(col).deleteMany({});
      console.log(`  ✓ Emptied collection: ${col} (${res.deletedCount} deleted)`);
    } catch (e) {
      console.warn(`  - Skipping ${col}:`, e.message);
    }
  }

  // Clear uploads directory
  if (fs.existsSync(UPLOADS_DIR)) {
    const entries = fs.readdirSync(UPLOADS_DIR);
    for (const entry of entries) {
      const p = path.join(UPLOADS_DIR, entry);
      fs.rmSync(p, { recursive: true, force: true });
    }
    console.log(`  ✓ Emptied uploads directory: ${UPLOADS_DIR}`);
  }

  console.log('\n✅ All storage and database data completely wiped clean.\n');
}

async function main() {
  const args = process.argv.slice(2);
  const isCleanTests = args.includes('--clean-tests');
  const isWipeAll = args.includes('--wipe-all');
  const isConfirmed = args.includes('--confirm');

  const client = new MongoClient(MONGODB_URI);
  await client.connect();
  const db = client.db(DB_NAME);

  try {
    if (isWipeAll) {
      if (!isConfirmed) {
        console.error('\n🛑 SAFETY WARNING: To wipe all data, you must pass the --confirm flag:');
        console.error('   node clean-storage.mjs --wipe-all --confirm\n');
        process.exit(1);
      }
      await wipeAll(db);
    } else if (isCleanTests) {
      await cleanTestFixtures(db);
      await inspectStorage(db);
    } else {
      // Default: inspect only
      await inspectStorage(db);
      console.log('💡 To clean test data safely while preserving real users:');
      console.log('   npm run storage:clean-tests\n');
      console.log('💡 To wipe all data completely for a clean slate:');
      console.log('   npm run storage:wipe-all\n');
    }
  } finally {
    await client.close();
  }
}

main().catch(err => {
  console.error('Fatal storage utility error:', err);
  process.exit(1);
});
